name: benaiah_okwukwe_anukem
description: Furniture Retail E-Store
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  badges: ^3.1.1
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  http: ^1.0.0
  iconly: ^1.0.1
  intl: ^0.18.0
  lottie: ^2.4.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
#    - assets/fonts/
